# @format

version: "3.0"

services:
  api:
    container_name: "twitter-api"
    volumes:
      - ./src:/workspace/src:cached
      - ./test:/workspace/test:cached
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - .env
    working_dir: /workspace/src
    command: pipenv run uvicorn fastapi_main:app --reload --port=8080 --host=0.0.0.0
    ports:
      - 10326:8080
    tty: true
